FROM nvidia/cuda:13.0.1-devel-ubuntu22.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        software-properties-common \
        git \
        libgl1-mesa-glx \
        libglib2.0-0 \
        libsm6 \
        libxext6 \
        libxrender1 && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        python3.11 \
        python3.11-venv \
        python3.11-dev \
        python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Make python3.11 the default
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1

# RUN apt-get update && \
#     DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python3-pip git && \
#     rm -rf /var/lib/apt/lists/*

RUN python3.11 -m pip install --upgrade pip
RUN pip3 install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu129

# RUN pip3 install --no-cache-dir torch==2.5.0+cu1301 \
#      --extra-index-url https://download.pytorch.org/whl/cu1301

WORKDIR /opt
